#pragma once

#define GET_PROCESS_BASE_ADDRESS_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0701, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _GET_PROCESS_BASE_ADDRESS_PARAM {
	DWORD ProcessId;
	DWORD64 BaseAddress;
} GET_PROCESS_BASE_ADDRESS_PARAM, *PGET_PROCESS_BASE_ADDRESS_PARAM;

#define MEMORY_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0702, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _MEMORY_READ_PARAM {
	DWORD ProcessId;
	DWORD64 Address;
	BYTE Value[10485760]; // 10MiB
	DWORD Size;
} MEMORY_READ_PARAM, *PMEMORY_READ_PARAM;

#define MEMORY_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0703, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _MEMORY_WRITE_PARAM {
	DWORD ProcessId;
	DWORD64 Address;
	BYTE Value[10485760]; // 10MiB
	DWORD Size;
} MEMORY_WRITE_PARAM, *PMEMORY_WRITE_PARAM;
