#pragma once

#define INITIALIZE_DRIVER_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0701, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _INITIALIZE_DRIVER_PARAM {
	_In_	DWORD	ClientProcessId;
	_In_	DWORD	TargetProcessId;
	_Out_	DWORD64	TargetProcessBaseAddress;
} INITIALIZE_DRIVER_PARAM, *PINITIALIZE_DRIVER_PARAM;

#define READ_MEMORY_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0702, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _READ_MEMORY_PARAM {
	_Out_	DWORD64	ClientBufferAddress;
	_In_	DWORD64	TargetBufferAddress;
	_In_	DWORD64 Size;
} READ_MEMORY_PARAM, *PREAD_MEMORY_PARAM;

#define WRITE_MEMORY_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0703, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _WRITE_MEMORY_PARAM {
	_In_	DWORD64	ClientBufferAddress;
	_In_	DWORD64	TargetBufferAddress;
	_In_	DWORD64	Size;
} WRITE_MEMORY_PARAM, *PWRITE_MEMORY_PARAM;
