#pragma once

#define MEMORY_READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0701, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _MEMORY_READ_PARAM {
	DWORD ProcessId;
	DWORD64 Address;
	BYTE Value[524288];
	BYTE Value2[524288];
	BYTE Value3[524288];
	DWORD Size;
} MEMORY_READ_PARAM, *PMEMORY_READ_PARAM;

#define MEMORY_WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0702, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
typedef struct _MEMORY_WRITE_PARAM {
	DWORD ProcessId;
	DWORD64 Address;
	BYTE Value[1024];
	BYTE Value2[524288];
	BYTE Value3[524288];
	DWORD Size;
} MEMORY_WRITE_PARAM, *PMEMORY_WRITE_PARAM;
